FROM nginx:alpine
LABEL org.opencontainers.image.source="https://github.com/agustinbravop/utn-vault-website"
RUN printf '%s\n' 'server {' '    listen       80;' '    server_name  localhost;' '    location / {' '        root   /usr/share/nginx/html;' '        index  index.html;' '        try_files $uri $uri.html $uri/ =404;' '    }' '    error_page   404  /404.html;' '    location = /404.html {' '        root   /usr/share/nginx/html;' '    }' '}' > /etc/nginx/conf.d/default.conf
COPY public /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
